config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
    scope module: :public do
    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :orders, only:[:new,:index,:show,:create]do
      collection do
        post :confirm
        get :complete
      end
    end
    
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :customers, only:[:show,:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdrawl
      end
    end

    resources :items, only:[:index,:show]
    # resource :favorites, only: [:create, :destroy]　実装予定
    resources :genres, only:[:show]

  end
  
  
  namespace :admin do
    root to: 'homes#top'
    
    
    resources :makings, only:[:update]
    resources :orders, only:[:edit,:update,:show]
    get "orders/history/:id" => "orders#history", as: "order_history"
    resources :order_details, only: [:update] 
    resources :customers, only:[:index,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update, :destroy]
    resources :items, only:[:index,:show,:new,:create,:edit,:update,:destroy]
    delete 'items/:id'  => 'items#destroy', as: "items_destroy"
  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code,presence: true
    validates :name,presence: true
    validates :address,presence: true
    
    def address_for_view
        self.postal_code + "　" + self.address + "　" + self.name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,(管理者のアカウント登録禁止)
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    validates :item_id,presence: true
    validates :amount,presence: true
    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :phone_number,presence: true
  validates :email,presence: true
  validates :password,presence: true
  

  # 退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  
  def name
    [first_name, last_name].join(' ')
  end
  
  # def full_name
  #   self.last_name + " " + self.first_name
  # end
  
  
  # def favorited_by?(item)  #item_idがFavoritesテーブル内に存在（exists?）するかどうかを判断
  #   favorites.exists?(item_id: item.id)  #以前にitem_idがテーブルに保存されているかを調べる
  # end
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    # belongs_to :genre
    # belongs_to :customer
    # belongs_to :item
    
    # # 1人ができるいいね数は1つまで
    # validates_uniqueness_of :item_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    # has_many :favorites,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    belongs_to :customer
    # has_many :favorites,dependent: :destroy　実装予定
    has_many :cart_items,dependent: :destroy
    has_many :order_details,dependent: :destroy
    
    
    # validates :image,presence:true
    validates :genre_id, presence: true  #空でないこと
    validates :name,presence:true
    validates :introduction,presence:true
    validates :genre,presence:true
    # validates :add_tax_price,presence:true
    validates :is_active, inclusion: { in: [true, false] }
    
    def get_image
        (image.attached?) ? image : 'no_image.jpg'
    end
    
    
    ## 消費税を求めるメソッド
    def with_tax_price
        (price * 1.1).floor
    end
        
    def favorited_by?(customer)  #customer_idがFavoritesテーブル内に存在（exists?）するかどうかを判断
      favorites.exists?(customer_id: customer.id)  #以前にcustomer_idがテーブルに保存されているかを調べる
    end

    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items,through: :order_detail
    has_many :order_details
    has_many :order_items
    belongs_to :customer
    
    validates :postal_code,presence: true
    validates :name,presence: true
    validates :address,presence: true
    
    enum status: { waiting_payment: 0, payment_confirmation: 1, under_prodction: 2, preparing_ship: 3, sent: 4 }
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum making_status: { work_wrong: 0, work_wait: 1, work_middle: 2, work_completion: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin! 
  def top
    @items = Item.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin! 
  
  def index
    @items = Item.page(params[:page]).per(10)
    @item = Item.all
  end

  def new
    @item = Item.new
  end
  
   def create
    @item = Item.new(item_params)
      if @item.save then
         flash[:notice] = '新しい商品を登録しました。'
         redirect_to admin_items_path(@item)
      else
         logger.debug @item.errors.inspect
        flash[:notice] = '商品を登録できませんでした。'
        render new_admin_item_path
      end
   end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
      flash[:notice] = '商品情報を更新しました'
    else
      render :"edit"
      flash[:notice] = '商品情報の更新に失敗しました'
    end
  end
  
  
  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to admin_items_path, notice: "商品を削除しました。"
  end
  
  private
  
  def item_params
  	params.require(:item).permit(:name, :introduction, :genre_id, :price, :is_active, :store, :image)
  end

end

app/controllers/admin/shops_controller.rb
class Admin::ShopsController < ApplicationController
  def index
  end

  def edit
  end

  def update
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  #会員のページにアクセスする前にconfigure_permitted_parametersを実行する
  
  def after_admin_sign_in_path_for(resource_or_scope)　#複数のdeviceがある場合この記述をする
    if resource.is_a?(Admin)
       admin_orders_path
    else
       root_path
    end
  end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])   
    #sign_upの際に許可するメソッド
  end
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/oders_helper.rb
module Admin::OdersHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/admin/items/_error.html.erb
<% if item.errors.any? %>
  <div class="alert alert-danger" role="alert">
   <h4 class="alert-heading"><%= pluralize(item.errors.count, "error") %></h4>
    <p><%= pluralize(item.errors.count, "error") %> prohibited this object from being saved: not successfully</p>
      <hr>
    <p class="mb-0">
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
       <% end %>
    </p>
  </div>
<% end %>

app/views/admin/items/edit.html.erb
<%= render 'error', item: @item %>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">商品編集</h1>
    </div>
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <%= form_with model: @item, url: admin_item_path do |f| %>
        <table class="table table-hover">
          <tr>
            <th><%= f.label :商品画像 %></th>
            <td><%= f.file_field :image, placeholder: "選択されていません", accept: "image/*" %></td>
          </tr>
          <tr>
            <th><%= f.label :ブランド %></th>
            <td><%= f.text_field :store, size: 40, placeholder: "ブランド名" %></td>
          </tr>
          <tr>
            <th><%= f.label :商品名 %></th>
            <td><%= f.text_field :name, size: 40, placeholder: "商品名" %></td>
          </tr>
          <tr>
            <th><%= f.label :商品説明 %></th>
            <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "60x5", autofocus: true, autocomlete: "introduction" %></td>
          </tr>
          <tr>
            <th><%= f.label:ジャンル %></th>
            <td><%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"} %></td>
          </tr>
          <tr>
            <th><%= f.label :税抜価格 %></th>
            <td><%= f.text_field :price, autofocus: true, autocomlete: "price", placeholder: 1000 %>円</td>
          </tr>
          <tr>
            <th><%= f.label :販売ステータス %></th>
            <td>
              <%= f.radio_button :is_active, :true %>
                <%= f.label :is_active,"販売中" %>
                <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, "販売停止中" %>
            </td>
          </tr>
        </table>
          <div class="col-md-10 offset-1" style="text-align: right;">
            <%= f.submit "更新", class: "btn btn-warning" %>
          </div>
    </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">商品一覧</h1>
    </div>
    <h1 class="col-md-10 offset-1" style="text-align: right;margin-top:30px; ">
      <%= link_to "＋ 新規追加", new_admin_item_path, class: "btn btn-dark" %>
    </h1>
    <div class="col-md-10 offset-1">
      <table class="table table-hover">
        <tr>
          <th></th>
          <th>ブランド名</th>
          <th>商品名</th>
          <th>価格</th>
          <th>ステータス</th>
        </tr>
        <tbody>
          <% @item.each do |item| %>
            <tr>
              <td>
                <% if item.image.attached? %>
                  <%= image_tag item.image, class: "thumb-160-100" %>
                <% else %>
                      <%= image_tag 'no_image.jpg', class: "thumb-160-100" %>
                <% end %>
              </td>
              <td><%= item.store %></td>
              <td><%= link_to item.name,admin_item_path(item.id) %></td>
              <td><%= item.price %>円</td>
              <td>
                <% if item.is_active %>
                  <!--is_activeの情報を取得して在庫があるかチェック--><b class="text-success">
                      販売中</b>
                  <%# trueの時の表示 %>
                <% else %> <b class="text-secondary">
                      販売停止中</b>
                      <%# falseの時の表示 %>
                <% end %>
              </td>
              <td>
                <%= link_to "編集する", edit_admin_item_path(item.id), class: "btn btn-warning" %>
              </td>
            </tr>
            <% end %>
        <%= paginate @items %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<%= render 'error', item: @item %>

<div class="container">
  <div class="row">
      <div class="col-md-10 offset-1" style="margin-top:30px; ">
        <h1 class="border-bottom">商品新規登録</h1>
      </div>
      <div class="col-md-10 offset-1" style="form-align: center;margin-top:30px; ">
        <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>
          <table class="table table-hover">
            <tr>
              <th><%= f.label :商品画像 %></th>
              <td><%= f.file_field :image, placeholder: "選択されていません", accept: "image/*" %></td>
            </tr>
            <tr>
              <th><%= f.label :ブランド %></th>
              <td><%= f.text_field :store, placeholder: "ブランド名" %></td>
            </tr>
            <tr>
              <th><%= f.label :商品名 %></th>
              <td><%= f.text_field :name, placeholder: "商品名" %></td>
            </tr>
            <tr>
              <th><%= f.label :商品説明 %></th>
              <td><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", size: "60x5", autofocus: true, autocomlete: "introduction" %></td>
            </tr>
            <tr>
              <th><%= f.label:ジャンル %></th>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name ,{}, include_blank: "選択してください" %></td>
            </tr>
            <tr>
              <th><%= f.label :税抜価格 %></th>
              <td><%= f.text_field :price, size: 40, autofocus: true, autocomlete: "price", placeholder: 1000 %>円</td>
            </tr>
            
            <tr>
              <th><%= f.label :販売ステータス %></th>
              <td>
                <%= f.radio_button :is_active, :true %>
                  <%= f.label :is_active,"販売中", value: true %>
                  <%= f.radio_button :is_active, :false %>
                <%= f.label :is_active, "販売停止中", value: false %>
              </td>
            </tr>

          </table>
          <div class="col-md-10 offset-1" style="text-align: right;">
           <%= f.submit "新規登録", class: "btn btn-warning" %>
          </div>
      </div>
        <% end %>
     </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">商品詳細</h1>
    </div>
  <div class="col-md-2 offset-1" style="text-align: light;">
     <table class="table table-hover">
      <tr>
        <% if @item.image.attached? %>
          <%= image_tag @item.image, class: "thumb-200-200" %>
        <% else %>
          <%= image_tag 'no_image_jpg', class: "thumb-200-200"%>
        <% end %>
      </tr>
     </table>
  </div>
  <div class="col-md-8 offset-1" style="text-align: light;">
    <table class="table">
        <tr>
          <th>商品名</th>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <th>商品説明</th>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <th>税込価格<br>(税抜価格) </th>
          <td>
           <%= @item.with_tax_price.to_s(:delimited) %>円<br>
           <%= @item.price.to_s(:delimited) %>円
          </td>
        </tr>
        <tr>
          <th>販売ステータス</th>
          <td class="font-weight-bold text-success">
            <% if @item.is_active %> <%# is_activeの情報を取得して在庫があるかチェック %> 
              販売中 <%# trueの表示がでる %>
            <% else %>
              販売停止中<%# falseの表示がでる %>
            <% end %>
          </td>
        </tr>
    </table>
      <div class="col-md-10 offset-1" style="text-align: right;">
        <%= link_to '編集', edit_admin_item_path(@item), class: "btn btn-success" %>
        <%= link_to '削除', admin_items_destroy_path(@item), method: :delete, class: "btn btn-danger" %>
      </div>
  </div>
</div>