config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
    scope module: :public do
    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :orders, only:[:new,:index,:show,:create]do
      collection do
        post :confirm
        get :complete
      end
    end
    
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :customers, only:[:show,:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdrawl
      end
    end

    resources :items, only:[:index,:show]
    # resource :favorites, only: [:create, :destroy]　実装予定
    resources :genres, only:[:show]

  end
  
  
  namespace :admin do
    root to: 'homes#top'
    
    
    resources :makings, only:[:update]
    resources :orders, only:[:edit,:update,:show]
    get "orders/history/:id" => "orders#history", as: "order_history"
    resources :order_details, only: [:update] 
    resources :customers, only:[:index,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update, :destroy]
    resources :items, only:[:index,:show,:new,:create,:edit,:update,:destroy]
    delete 'items/:id'  => 'items#destroy', as: "items_destroy"
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :phone_number,presence: true
  validates :email,presence: true
  validates :password,presence: true
  

  # 退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  
  def name
    [first_name, last_name].join(' ')
  end
  
  # def full_name
  #   self.last_name + " " + self.first_name
  # end
  
  
  # def favorited_by?(item)  #item_idがFavoritesテーブル内に存在（exists?）するかどうかを判断
  #   favorites.exists?(item_id: item.id)  #以前にitem_idがテーブルに保存されているかを調べる
  # end
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
      flash[:notice] = '会員情報が更新されました。'
    else
      render "edit"
    end
  end
  
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana,:first_name_kana, 
    :postal_code, :address,:phone_number, :email, :is_deleted)
  end
  
end

app/views/admin/customers/edit.html.erb
<% if @customer.errors.any? %>
  <div id="error_explanation" class="alert alert-danger">
    <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">会員情報編集画面</h1>
    </div>
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <%= form_with model: @customer, url: admin_customer_path(@customer.id), method: :patch do |f| %>
        <table class="table">
          <tbody>
            <tr>
              <td>会員ID</td>
              <td><%= @customer.id %></td>
            </tr>
            <tr><td>氏名</td>
              <td><%= f.text_field :last_name %><%= f.text_field :first_name %></td>
            </tr>
            <tr><td>フリガナ</td>
               <td><%= f.text_field :last_name_kana %><%= f.text_field :first_name_kana %></td>
            </tr>
            <tr><td>郵便番号</td>
              <td><%= f.text_field :postal_code %></td>
            </tr>
            <tr>
              <td>住所</td>
              <td><%= f.text_field :address, size: "47x5" %></td>
            </tr>
            <tr>
              <td>電話番号</td>
              <td><%= f.text_field :phone_number %></td>
            </tr>
            <tr>
              <td>メールアドレス</td>
              <td><%= f.text_field :email %></td>
            </tr>
            <tr>
              <td>会員ステータス</td>
               <td>
                  <%= f.radio_button :is_deleted, :false %> <%# is_deleted(退会フラグ)がfalse(初期値)なら'有効' %>
                    <%= f.label :is_deleted, "有効" %>  
                    <%= f.radio_button :is_deleted, :true %> <%# is_deleted(退会フラグ)がtrue(退会処理済み)なら'退会' %>
                  <%= f.label :is_deleted, "退会" %>
               </td>
            </tr>
          </tbody>
        </table>
        <div class="col-md-10 offset-1" style="text-align:right; margin-top:30px; ">
          <%= f.submit '変更を保存', class: "btn btn-dark" %>
        </div>
        <% end %>
    </div>
  </div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">会員情報一覧</h1>
    </div>
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <table class="table table-hover">
        <tr>
          <th>会員ID</th>
           <th>氏名</th>
           <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
        <tbody>
          <% @customers.each do |customer| %>
            <%# @publics = Public.allですべてのPublicユーザーの情報を取得して、順番に並べて表示 %>
              <tr>
                <!--<td><%#= customer.id %></td>-->
                 <td><%= link_to customer.id, admin_customer_path(customer.id)%></td>
                 <td><%= link_to customer.name, admin_customer_path(customer.id)%></td>
                 <td><%= customer.email %></td>
                <td>
                  <% if customer.is_deleted %>
                    <b class="text-secondary">退会</b><%# is_deletedの情報を取得して退会済みかチェック %> 
                  <% else %>
                    <b class="text-success">有効</b><%# true(退会済み)の時の表示 %> 
                  <% end %><%# false(初期値)の時の表示 %>
              </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <h1 class="border-bottom">会員詳細画面</h1>
    </div>
    <div class="col-md-10 offset-1" style="margin-top:30px; ">
      <table class="table">
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %><%= @customer.first_name %>
          </td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %><%= @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted %><%# is_deletedの情報を取得して退会済みかチェック %> 
              <b class="text-secondary">退会</b><%# true(退会済み)の時の表示 %>
            <% else %>
              <b class="text-success">有効</b> <%# false(初期値)の時の表示 %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
      <div class="col-md-10 offset-1" style="text-align:right; margin-top:30px; ">
        <%= link_to '編集する', edit_admin_customer_path(@customer.id), class: "btn btn-dark" %>
          <%= link_to "注文履歴一覧を見る", admin_order_history_path(@customer), class: "btn btn-dark" %>
      </div>
  </div>
</div>