config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
    scope module: :public do
    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :orders, only:[:new,:index,:show,:create]do
      collection do
        post :confirm
        get :complete
      end
    end
    
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :customers, only:[:show,:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdrawl
      end
    end

    resources :items, only:[:index,:show]
    # resource :favorites, only: [:create, :destroy]　実装予定
    resources :genres, only:[:show]

  end
  
  
  namespace :admin do
    root to: 'homes#top'
    
    
    resources :makings, only:[:update]
    resources :orders, only:[:edit,:update,:show]
    get "orders/history/:id" => "orders#history", as: "order_history"
    resources :order_details, only: [:update] 
    resources :customers, only:[:index,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update, :destroy]
    resources :items, only:[:index,:show,:new,:create,:edit,:update,:destroy]
    delete 'items/:id'  => 'items#destroy', as: "items_destroy"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    # has_many :favorites,dependent: :destroy
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
     @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path #編集一覧に戻る
      flash[:notice] = '新しいジャンルを登録しました。'
    else
      @genres = Genre.all
      flash[:notice] = '新しいジャンルを登録しました。'
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
      flash[:notice] = "ジャンルが変更されました。"
    else
      render :edit
    end
  end
  
  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    flash[:notice] = "ジャンルを削除しました。"
    redirect_to admin_genres_path  #編集一覧に戻る
  end
  
  private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h2 class="p-3 mb-2">ジャンル編集</h2>
      <tbody>
    <%= form_with model: @genre, url: admin_genre_path do |f| %>
      <div class="table" style="margin-top: 70px;">
        <tr> <label for="name">ジャンル名</label>
          <td>
            <%= f.text_field :name %>
            <%= f.submit "変更を保存", class: "btn btn-outline-success" %>
          </td>
        </tr>
      </div>
    <% end %>
      </tbody>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <thead>
        <h2 class="p-3 mb-2">ジャンル一覧・追加</h2><br> </thead>
      <tbody>
        <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
          <div class="table" style="margin-top: 60px;"> <label>ジャンル名</label>
            <%= f.text_field :name, placeholder: "ジャンル名" %>
              <%= f.submit '新規登録', class: "btn btn-outline-success" %>
          </div>
      </tbody>
    </div>
  </div>
  <% end %> <br>
    <!--二段に切り替える-->
    <div class="row ">
      <div class="col-md-12">
        <table class="table" style="margin-top: 60px;">
          <thead>
            <tr class="active">
              <h4>ジャンル一覧</h4>
            </tr>
          </thead>
          <tbody>
            <% @genres.each do |genre| %>
              <tr>
                <td>
                  <%= genre.name %>
                </td>
                <td>
                  <%= link_to "編集", edit_admin_genre_path(genre) ,class: "btn btn-outline-success" %>
                  <%= link_to '削除', admin_genre_path(genre), method: :delete, class: "btn btn-outline-success" %>
                </td>
              </tr>
              <% end %>
          </tbody>
        </table>
      </div>
    </div>
</div>