config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }
  
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'
  
    scope module: :public do
    resources :addresses, only:[:index,:edit,:create,:update,:destroy]
    resources :orders, only:[:new,:index,:show,:create]do
      collection do
        post :confirm
        get :complete
      end
    end
    
    resources :cart_items, only:[:index,:create,:update,:destroy] do
      collection do
        delete :destroy_all
      end
    end

    resources :customers, only:[:show,:edit,:update] do
      collection do
        get :unsubscribe
        patch :withdrawl
      end
    end

    resources :items, only:[:index,:show]
    # resource :favorites, only: [:create, :destroy]　実装予定
    resources :genres, only:[:show]

  end
  
  
  namespace :admin do
    root to: 'homes#top'
    
    
    resources :makings, only:[:update]
    resources :orders, only:[:edit,:update,:show]
    get "orders/history/:id" => "orders#history", as: "order_history"
    resources :order_details, only: [:update] 
    resources :customers, only:[:index,:show,:edit,:update]
    resources :genres, only:[:index,:create,:edit,:update, :destroy]
    resources :items, only:[:index,:show,:new,:create,:edit,:update,:destroy]
    delete 'items/:id'  => 'items#destroy', as: "items_destroy"
  end

end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :customer
    
    validates :postal_code,presence: true
    validates :name,presence: true
    validates :address,presence: true
    
    def address_for_view
        self.postal_code + "　" + self.address + "　" + self.name
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,(管理者のアカウント登録禁止)
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    belongs_to :item
    belongs_to :customer
    
    validates :item_id,presence: true
    validates :amount,presence: true
    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :orders, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :favorites,dependent: :destroy
  has_many :items, dependent: :destroy
  
  validates :last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :postal_code,presence: true
  validates :address,presence: true
  validates :phone_number,presence: true
  validates :email,presence: true
  validates :password,presence: true
  

  # 退会機能
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  
  def name
    [first_name, last_name].join(' ')
  end
  
  # def full_name
  #   self.last_name + " " + self.first_name
  # end
  
  
  # def favorited_by?(item)  #item_idがFavoritesテーブル内に存在（exists?）するかどうかを判断
  #   favorites.exists?(item_id: item.id)  #以前にitem_idがテーブルに保存されているかを調べる
  # end
  
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    # belongs_to :genre
    # belongs_to :customer
    # belongs_to :item
    
    # # 1人ができるいいね数は1つまで
    # validates_uniqueness_of :item_id, scope: :customer_id
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :items
    # has_many :favorites,dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    belongs_to :genre
    belongs_to :customer
    # has_many :favorites,dependent: :destroy　実装予定
    has_many :cart_items,dependent: :destroy
    has_many :order_details,dependent: :destroy
    
    
    # validates :image,presence:true
    validates :genre_id, presence: true  #空でないこと
    validates :name,presence:true
    validates :introduction,presence:true
    validates :genre,presence:true
    # validates :add_tax_price,presence:true
    validates :is_active, inclusion: { in: [true, false] }
    
    def get_image
        (image.attached?) ? image : 'no_image.jpg'
    end
    
    
    ## 消費税を求めるメソッド
    def with_tax_price
        (price * 1.1).floor
    end
        
    def favorited_by?(customer)  #customer_idがFavoritesテーブル内に存在（exists?）するかどうかを判断
      favorites.exists?(customer_id: customer.id)  #以前にcustomer_idがテーブルに保存されているかを調べる
    end

    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :items,through: :order_detail
    has_many :order_details
    has_many :order_items
    belongs_to :customer
    
    validates :postal_code,presence: true
    validates :name,presence: true
    validates :address,presence: true
    
    enum status: { waiting_payment: 0, payment_confirmation: 1, under_prodction: 2, preparing_ship: 3, sent: 4 }
    enum payment_method: { credit_card: 0, transfer: 1 }
    
    def subtotal  #小計を求めるコマンド
        item.with_tax_price * amount
    end
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    belongs_to :item
    belongs_to :order
    
    enum making_status: { work_wrong: 0, work_wait: 1, work_middle: 2, work_completion: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin! 
  def top
    @items = Item.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 
  #会員のページにアクセスする前にconfigure_permitted_parametersを実行する
  
  def after_admin_sign_in_path_for(resource_or_scope)　#複数のdeviceがある場合この記述をする
    if resource.is_a?(Admin)
       admin_orders_path
    else
       root_path
    end
  end
  
  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :phone_number])   
    #sign_upの際に許可するメソッド
  end
end

app/helpers/admin/costomers_helper.rb
module Admin::CostomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/oders_helper.rb
module Admin::OdersHelper
end

app/helpers/admin/shops_helper.rb
module Admin::ShopsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<!--%- if devise_mapping.registerable? && controller_name != 'registrations' %>-->
<!--  %= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<!--% end %>-->

<!--削除内容はカリキュラムに記載されている-->

app/views/layouts/_footer.html.erb
<footer>
  <nav class="bg-white">
  <div class="container">
    <div class="row">
      <div class="col-md-12" style="text-align: center; line-height: 100px;">
        <p>CopyRight Machiokoshi.inc</p>
      </div>
    </div>
  </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="header_a">
  <div class="logo">Machiokoshi</div>
  
    <nav>
      <ul>
        <% if customer_signed_in? %>
          <li><a href="/">Home</a></li>
          <li><a href="/public/homes/about">About us</a></li>
          <li><a href="/customers/:id">My Page</a></li>
          <li><a href="/cart_items">Cart</a></li>
          <li><%= link_to "Logout", destroy_customer_session_path, method: :delete %></li>
        <% else %>
          <li><a href="/">Home</a></li>
          <li><a href="/public/homes/about">About us</a></li>
          <li><a href="/cart_items">Cart</a></li>
          <li><a href="/customers/sign_in">Log in</a></li>
      </ul>
      <% end %>
    </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>MachiokoshiApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.3.2/swiper-bundle.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <!--CSS-->
    <%#= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--FONT-->
    <link href="https://fonts.googleapis.com/css2?family=Fascinate+Inline&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if flash[:notice] %>
     <div class="notification is-info">
      <p class="notice"><%= notice %></p>
     </div>
    <% end %>
    
    <% if flash[:notice] %>
     <div class="notification is-info">
       <p class="alert"><%= alert %></p>
     </div>
    <% end %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.3.2/swiper-bundle.min.js"></script>
    
    
    <%= yield %>
    
    <footer>
      <%= render 'layouts/footer' %>
    </footer>
    
  </body>
</html>